name: Java CI Backend

# Se ejecuta cada vez que haces push a 'main' o 'develop'
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    # Le dice a GitHub que use un servidor de Ubuntu
    runs-on: ubuntu-latest

    steps:
    # 1. Clona tu repositorio
    - uses: actions/checkout@v4

    # 2. Configura el JDK de Java 
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # 3. Mueve a la carpeta Backend y ejecuta las pruebas
    - name: Build and Test with Maven
      run: |
        cd Backend 
        mvn test
